src/gadgetio.cxx
src/hdfio.cxx
src/ramsesio.cxx
src/substructureproperties.cxx
src/swiftinterface.cxx
src/ui.cxx

It might be best not to merge this immediately but I'm making a pull request to document this fix.
Here I've tried to cherry pick the changes from Pascal's expandedproperties branch which are needed to fix the incorrect m200 halo masses which Velociraptor was generating. The problem was that the density threshold used for the spherical mass estimates had an incorrect dependence on redshift so it diverged from the correct value as redshift increased. The calculation of the threshold was duplicated over the various read routines and the SWIFT interface. In the fixed version there's a single function to do the calculation.
So far I've checked that this generates the same m200 mean and critical mass functions as the EAGLE code at low and high redshift in the 25Mpc DMONLY box. I haven't tried …

Correct m200 mean halo masses

---

doc/usage.rst
examples/sample_swifthydro_3dfof_subhalo_extra_properties.cfg
src/substructureproperties.cxx

Updated example file to highlight parameter that sets the reference particle type.
To be tested first by ICRAR test team, only then it will be merged back into `master`.

Update to implement specific particle types for min potential reference

---

src/unbind.cxx

When OpenMP is not used these two variables were not initialized and led
to segmentation faults as this resulted in the code dereferencing
pointers that hadn't been initialized.

Add variable initialization

---

src/allvars.h
src/substructureproperties.cxx

The different functions calculating accumulated metrics over the extra
gas/star/bh properties shared a common signature (made explicitly by the
ExtraPropFunc typedef) signaling that a double value should be returned.
However, in reality none of these functions performed a return. This in
seems to have contributed to the introduction of UB, resulting in
hard-to-debug errors.
This commit modifies the ExtraPropFunc typedef to indicate that
functions adjusting to this type don't need to return a double, and
should return void instead. The signature of all the functions that are
used through this typedef are then adjusted to reflect this change.
Although it looks unrelated, this patch fixes the problem described in
issue #18. This is consistent with the fact that the problem surfaced
only …

Remove double as return type of ExtraPropFunc

---

src/substructureproperties.cxx

Particles have four optional sets of properties: hydro, star, black hole, and extra dark matter. Because they are optional, they must be checked first before using them. If they have not been set by the time they are used, an error will be caused by dereferencing uninitialized pointers.
This check is not always in place, and this commit adds some missing checks. They are in CalculateApertureQuantities and in the different GetExtra*Properties functions. From what I can tell, until now the code seemed to have handled this by assuming that the properties are always set for the particles that are passed to these functions. This is not true however for particles passed on by the swift-vr invocation interface.
This addresses the immediate problem with the crashes reported in #13. The issue …

Add check-before-use for Particle properties

---

src/swiftinterface.cxx
src/swiftinterface.h

This modifies the Swift interface so that Swift can request that Velociraptor return the indexes of the most bound particles in the halos it finds. On the Swift side, we can then use that information to output the particles we need for 'orphan' galaxies in semi-analytic models (i.e. galaxies which are no longer associated with a resolved halo.)
The corresponding merge request on the Swift side is at https://gitlab.cosma.dur.ac.uk/swift/swiftsim/merge_requests/1131.
(moved over from Pascal's repository)

Return most bound particle indexes when running on the fly in Swift

---

src/io.cxx

The function used CosmicTimeCalc returned the age in years and not the internal units of the input table. I corrected this by using
the parameter stellar_age_to_yr provided in the input parameter.

Correcting ages to follow internal units of input

---

src/main.cxx

These are fixes to suppress warnings due to VR using `omp_{get,set}_nested`, which is deprecated in OpenMP 5. The fixes are mostly in NBodylib, which checks the compile-time OpenMP version (there's no way to check the runtime version) and decides whether to use the old functions, or the newer alternatives.
I took the chance of cleaning a bit the code around these function calls, trying to reduce duplication and mental load.

OpenMP 5 fixes

---

src/proto.h
src/utilities.cxx

GetMilliSpan is not called by anyone (not even in TreeFrog), and
GetMilliCount was only called by GetMilliSpan. On top of this,
GetMilliCount used ftime() internally, which was removed in
POSIX.1-2008 (and therefore has been marked as deprecated in GNU libc).
This addresses #29.

Remove ftime usage

---

.travis.yml
.travis/install.sh

A fix for a fix. OpenMP-disabled builds were accidentally broken after #25. Here were're adding OpenMP-disable builds and fixing the broken build.

Omp 5 fixes

---

src/hdfitems.h

This addresses #24. When writing multidimensional output datasets in parallel mode the offsets into the dataset were calculated incorrectly.
There were multiple copies of the write_dataset_nd method in hdfitems.h, one templated and one taking a void * pointer for the input data. Rather than fix them both I've made the templated version just call the void * version with the data type parameter set. This is how it already works for 1D datasets.
Still needs testing.

Correct output of multidimensional datasets when using parallel HDF5

---

src/io.cxx

When using parallel HDF5, Velociraptor writes multiple output files if MPI_number_of_tasks_per_write is less than the number of MPI ranks. This is implemented by making one communicator for each output file. All of the ranks in a communicator do a collective write to one output file. The files also contain some metadata which is written in serial mode by the first rank in the communicator.
If we have Calculate_radial_profiles=1 and are writing multiple files then the metadata is missing from all of the .profile files except the first one because only the first rank in MPI_COMM_WORLD writes the metadata. I think this is just a mistake because the other types of output (e.g. .properties) are not written like this.
This pull request changes the condition to write the metadata datasets so …

Write metadata to all .profile files when using parallel HDF5

---

CMakeLists.txt

Enabling this policy silences warnings seen in cosma (but likely to
happen in other places as well) when compiling VR with cmake >= 3.12,
and after loading modules that define <package>_ROOT environment
variables.
In particular, in cosma this was seen when find_package(MPI) ran because
there was an MPI_ROOT environment variable defined after loading the mpi
module in that system. This used to work (and continues to work) without
this policy because FindMPI looks for an MPI compiler in the PATH;
enabling the policy will not interfere with this, so there is no harm on
enabling it. Moreover, this might be helpful in other systems to find
not only MPI, but other packages.
This was highlighted by Stuart Mcalpine and John Helly during #33.

Enable CMP0074 policy when available

---

src/search.cxx
src/swiftinterface.cxx

Prevent crash in AdjustStructureForPeriod when using one MPI rank

---

src/hdfitems.h

In HDF5 1.12 H5Oget_info is a macro that points either to H5Oget_info1
or H5Oget_info3, which have different signatures. This patch checks the
HDF5 version we are compiling against and uses the correct signature to
invoke this function. The same applies to H5Oget_info_by_name{,3}.
This fix is based on pelahi@72f90bf but is not a direct cherry-pick, as
the original contained more changes than what I'd like to bring, plus it
doesn't correctly invoke (the new) H5Oget_info with correct values.
This addresses #42.

Fix compilation against HDF5 1.12

---

src/hdfitems.h

This was noted in #45. In the past the macro was defined (with the typo)
within the same file, but later on its definition was moved out to the
cmake infrastructure, where the correct spelling was used, hence the
incorrectly-spelled #ifdef block now always evaluate to false.
Since the names used to define and check the macro matched in the past,
I suspect the code within the #ifdef block was indeed exercised at some
point, and that it is correct (and at least it doesn't look obviously
incorrect). Hopefully this is still the case, and we won't be
introducing a new bug by allowing this code to compile.

Fix macro name typo to enable HDF5 compression

---

src/ui.cxx

This code, as previously written, entered into the "if" body even when
no separator ("=") was found. By good chance this didn't cause any
issues: because of how std::string::substr works the two calls issued
using the position value "j" ended up not throwing exceptions, although
both the parameter name and value would end up being equal to the full
line. This in turn means none of the subsequent "if" statements that set
different options are invoked.
Although this was probably never seen in the wild because configuration
files are seldom incorrectly written, a warning was generated by
different compilers (depending on version and warning flags). Since the
code is quite warning-full we never paid much attention to it until now.
The new code now properly checks that the result of the find …

Fix incorrect parsing logic

---

src/search.cxx

These are minor leaks, and probably don't accumulate greatly over time.
Anyways they should be addressed. Better solutions of course should be
sought with time, including more automatic memory management via vector,
unique_ptr and the like.
This fix addresses the problems highlighted in #60.

Address two different memory leaks

---

src/substructureproperties.cxx

Two commits here, one purely ornamental (indentation) plus the actual fix. This was tested in cosma6 with the same config and input used in #63, after which the original error is gone and VR runs to completion.

Guard access to typeparts

---

src/substructureproperties.cxx

The massval variable was previously declared outside the confines of the
OpenMP parallel context, but it wasn't declared as a private variable
during the omp pragma. This led to race conditions when using its values
from different threads, which eventually resulted on invalid SO mass
quantities for almost all the values calculated within GetSOMasses.
This commit removes the declaration of massval at the beginning of the
GetSOMasses function, and moves it to the innermost context possible,
ensuring its value is not shared across threads, preventing race
conditions, and therefore fixing the values for the SO mass quantities
when running with OpenMP.
This addresses #62.

Declare massval within private OpenMP context

---

src/CMakeLists.txt
src/exceptions.cxx
src/exceptions.h
src/localbgcomp.cxx
src/localfield.cxx

These changes address the problems highlighted in #53, at least for MPI-enabled cases. This PR is only to kick off the CI pipeline and double-check that those runs don't break; otherwise the changes have been tested on a couple of known failing inputs which are working again.

First batch of fixes for #53

---

src/allvars.h

This variable was not being initialised, and is never written to, and
thus code reading it cannot assume any consistent value, even between
two different runs.
This was reported in #79. Additionally we might want to add a new option
in the configuration file to allow users provide an arbitrary value for
this setting.

Give gas_sfr_threshold a default value of 0

---

src/substructureproperties.cxx

The SO_mass_interloper vector gets already filled with zeros when
resized, so there's no need to re-initialise it to zero again. Moreover,
this code didn't take into account the same condition used for resizing
the vector, and therefore it crashed when assigning values into an empty
vector.
This is the cause of the segmentation fault reported in #78.

Remove unnecessary, problematic vector initialisation

---

CMakeLists.txt

We hadn't been increasing the version number in NBodylib, and therefore
made it a bit difficult for users to remember to update their
submodules.

Update to new versioned release of NBodylib

---

src/unbind.cxx

There were a couple of problems with the old version of this code.
Firstly, it had an unused maxthreads variable, which has now been
removed. Secondly, and more importantly, it used a complex and incorrect
way of calculating the number of threads (stored in the nthreads
variable) that would be used in new "omp parallel" blocks: instead of
directly calling omp_get_max_threads and writing its result into
nthreads (the new behavior) it opened an "omp parallel" block and called
omp_get_num_threads, only on the first thread of the newly created
thread team. The result was then written back to nthreads.
Although this seems fine, it creates a race condition, as there is no
guarantee that thread #0 in the newly formed team is the same thread
from which the team was created. This in turn means …

Correctly calculate number of threads

---

src/ui.cxx

This is very similar to the warning reported in #58, but for some reason
I didn't fix it in 1ef9252. Here it goes.

Fix warning in configuration file parsing

---

src/allvars.h
src/ui.cxx
src/unbind.cxx

Does exactly what the title says :)
I think I set the default value correctly such that users who want the normal (old) behaviour are unaffected and can keep using their normal config files.
The rationale for this is that in the EAGLE family of model, we do heat particles to high temperatures when performing feedback but these particles are clearly not unbound.

Add the option to *not* consider the internal energy of the gas when performing the unbinding

---

src/hdfio.cxx
src/hdfitems.h
src/mpihdfio.cxx

Again, does what it says on the tin.
Two main changes:
- Add a new naming convention for hdf5 (value=9) for our series of runs (named FLAMINGO) with minimalistic snapshot content.
- When using this naming convention, the internal energies are not read and the field is just zeroed instead.

Add a new naming convention for the flamingo runs where the internal energy is not read in

---

src/hdfitems.h

The recent changes introduced during #99 added the new "flamingo" HDF5
convention, which doesn't read the InternalEnergies field (see 1e00be9
and f95f406). However, the first versions of the patches added this
line, which not only adds "InternalEnergies" to the list of dataset
names to be read, but also adds it incorrectly: it uses a plain "if"
instead of an "else if", causing eagle HDF5 input files to be expected
to have both "InternalEnergies" and "InternalEnergy" fields.

Remove incorrect dataset name addition

---

src/mpiroutines.cxx

The fix introduced in 1fa1e1e for #87 had itself a bug: we first stored
the size of the vector to be communicated as an int, and then declared
MPI we had an MPI_Int_t, which maps differently to MPI_LONG_LONG_INT or
MPI_INT depending on the LONGINT macro being defined or not. This
therefore doesn't work universally, leading to buffer overflows.
This commit declares the size variables as long long, and uses the
MPI_LONG_LONG_INT type explicitly during the MPI call. This makes the
communication safe regardless of the LONGINT macro being defined or not.

Use correct types for sending vector sizes

---

src/allvars.h
src/search.cxx
src/stf-fitting.h

A small collection of cleanups for warnings that have been appearing more and more when compiling with clang or newer gcc version. Many more warnings are available to be cleaned up when compiling with `-Wall`, but those are future work.

Warnings off

---

src/proto.h
src/unbind.cxx

The xpos argument in MarkCells doesn't need to be copied from the caller
site to the callee, a constant reference is enough.
Moreover, I found there was a misalignment in the signature of
MarkCells, with the declaration missing a Double *r2val argument. Since
the function is local to unbund.cxx I simply removed it from proto.h.

Avoid copying Coordinate argument

---

src/hdfio.cxx
src/mpihdfio.cxx

This is a follow up to #99. This second and final part deals with reading the header correctly, i.e. assuming it's a SWIFT snapshot and not a generic hdf5 file.

Flamingo io - Second part

---

src/hdfio.cxx

The broadcasting of the opt.bh_internalprop_output_names vector was
something that originally existed in the codebase, but was accidentally
removed in 4cdbd52 while fixing #100. This missing broadcast meant that
different ranks had different values in this vector, which ultimately
affects the HDF5 dataset count and names that are written by each rank.
When using parallel HDF5 writing this led to misaligned collective
calls, and therefore to the problems described in #102, which is the
issue this commit fixes.

Add missing broadcast

---

src/substructureproperties.cxx

When introduced, the temp variable followed the convention used for the
rest of the GetProperties local variables: it was declared at the top of
the function, then used whenever required. This variable however needed
to be private within each parallel OpenMP region, and therefore also
required being added to the "private" section of the required omp
pragmas.
This commit changes how temp is declared, moving it from the top of the
function to the innermost scope possible. This removes the need to keep
track of it in the private/shared lists of omp pragmas, making the code
less prone in the future.
This addresses the problem reported in #117.

Avoid using shared variable across parallel OpenMP regions

---

src/allvars.h
src/io.cxx
src/localfield.cxx
src/main.cxx
src/proto.h
src/search.cxx
src/substructureproperties.cxx
src/swiftinterface.cxx
src/ui.cxx
src/utilities.cxx

These are simple changes that, while not necessarily fixing #118, are self-contained, and might help figuring out where the memory is blowing exactly.

Improvements towards figuring out #118
